// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SocialIds
{
        public const string achievement_step_by_step = "CgkIxtr4y78NEAIQBQ"; // <GPGSID>
        public const string achievement_guru = "CgkIxtr4y78NEAIQBg"; // <GPGSID>
        public const string achievement_scholar = "CgkIxtr4y78NEAIQCQ"; // <GPGSID>
        public const string achievement_pro = "CgkIxtr4y78NEAIQCw"; // <GPGSID>
        public const string achievement_welcome = "CgkIxtr4y78NEAIQAw"; // <GPGSID>
        public const string achievement_godlike = "CgkIxtr4y78NEAIQBw"; // <GPGSID>
        public const string achievement_regular = "CgkIxtr4y78NEAIQCg"; // <GPGSID>
        public const string achievement_starting_to_get_into_this = "CgkIxtr4y78NEAIQBA"; // <GPGSID>
        public const string achievement_247 = "CgkIxtr4y78NEAIQDA"; // <GPGSID>
        public const string achievement_newbie = "CgkIxtr4y78NEAIQCA"; // <GPGSID>
        public const string leaderboard_sequence_leaderboard = "CgkIxtr4y78NEAIQDQ"; // <GPGSID>

}

